version: '3'

services:
  chatmaja:
    image: chatmaja/v2
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./db:/app/db
    environment:
      - HF_AUTH=your_huggingface_auth_token
