# images: https://hub.docker.com/_/python/tags?page=1&name=3.11
FROM python:3.11.8-bullseye

# arbitrary directory name, inside the container
WORKDIR /app

# copy from this directory to /app in the container all files according to .dockerignore
COPY requirements.txt /app/requirements.txt

# important to cache pip dependencies
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt
